version: "2"
services:
  blockchain:
    container_name: blockchain
    image: trustlab/ixo-blockchain:latest
    restart: always
    ports:
      - "46657:46657"
    logging:
      options:
        max-size: 30m
    volumes:
      - ./data/blockchain:/root/.ixo-node
    command: /go/src/github.com/ixofoundation/ixo-cosmos/bin/startBlockchain.sh
    
  rest:
    container_name: rest
    image: trustlab/ixo-blockchain:latest
    restart: always
    ports:
      - "1317:1317"
    links:
      - blockchain
    volumes:
      - ./data/blockchain:/root/.ixo-node
    command: ixocli rest-server -n tcp://blockchain:46657 -a tcp://0.0.0.0:1317
  
  block-sync:
    container_name: block-sync
    image: trustlab/ixo-block-sync:latest
    environment:
      - PORT=8080
      - MONGODB_URI=mongodb://block-sync-db:27017/block-sync
      - CHAIN_URI=blockchain:46657
    restart: always
    ports:
      - "8080:8080"
    links:
      - block-sync-db
      - blockchain
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
      
  block-sync-db:
    container_name: block-sync-db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
