accounts:
  - name: charlie
    coins: [ "1000000000uatom" ]
    mnemonic: special shuffle drill bachelor hundred pelican cushion glove acoustic tag pull riot shock artefact supply chef silk panda aspect crowd buyer sauce gap gain
    # address: ixo1xprmyxmxhk3j7vl929famszskac8z8l8hdqfty
  - name: dave
    coins: [ "1000000000uatom" ]
    mnemonic: strike mimic foil athlete copy satisfy beyond history try bulb section digital image winner recipe eight hand push margin ankle torch choice seed park
    # address: ixo1mv6wulhn9glhg8tayhzdlqg79w65f0nge352hx
validator:
  name: charlie
  staked: "100000000uatom"
faucet:
  name: dave
  coins: [ "100000uatom" ]
  port: 4502
build:
  binary: "ixod2"
host:
  rpc: ":26661"
  p2p: ":26660"
  prof: ":6063"
  grpc: ":9093"
  api: ":1320"
init:
  app:
    minimum-gas-prices: "0.025uatom"
genesis:
  chain_id: "pandora-3.2"
  app_state:
    staking:
      params:
        bond_denom: "uatom"
